const { getPool, sql } = require('../conectorMysql/conectorSqlServer');

class CalidadError extends Error {
  constructor(status, code, message) { super(message); this.status=status; this.code=code; }
}
const txt=(v)=>String(v??'').trim();
const num=(v,n,{min=0,nullable=false}={})=>{if(nullable&&(v===''||v==null))return null;const x=Number(v);if(!Number.isFinite(x)||x<min)throw new CalidadError(400,'VALIDATION_ERROR',`${n} no es valido.`);return x;};
const int=(v,n,o={})=>{const x=num(v,n,o);if(x===null)return null;if(!Number.isInteger(x))throw new CalidadError(400,'VALIDATION_ERROR',`${n} no es valido.`);return x;};
const key=(p)=>({tempCod:txt(p.tempCod),origin:int(p.origin,'origen',{min:1}),docType:int(p.docType,'tipo documento',{min:1}),guide:int(p.guide,'guia',{min:1}),producer:txt(p.producer),lot:int(p.lot,'lote',{min:1})});
const date=(v)=>{const x=txt(v);if(!/^\d{4}-\d{2}-\d{2}$/.test(x))throw new CalidadError(400,'VALIDATION_ERROR','Fecha de control no valida.');return x;};
const time=(v)=>{const x=txt(v);const match=/^(\d{2}):(\d{2})(?::(\d{2}))?$/.exec(x);if(!match||Number(match[1])>23||Number(match[2])>59||Number(match[3]||0)>59)throw new CalidadError(400,'VALIDATION_ERROR','Hora de control no valida.');return new Date(1970,0,1,Number(match[1]),Number(match[2]),Number(match[3]||0));};
const normalize=(p={})=>{
  const k=key(p); const damages=Array.isArray(p.damages)?p.damages:[]; const calibers=Array.isArray(p.calibers)?p.calibers:[];
  const colors=Array.isArray(p.colors)?p.colors:[]; const pests=Array.isArray(p.pests)?p.pests:[];
  const result={...k,inspectionDate:date(p.inspectionDate),inspectionTime:time(p.inspectionTime),pulpTemperature:num(p.pulpTemperature,'temperatura',{nullable:true}),sampleSize:int(p.sampleSize,'tamano muestra',{min:1}),
    durofelFruits:int(p.durofelFruits,'frutos Durofel',{nullable:true}),durofelAverage:num(p.durofelAverage,'AV Durofel',{nullable:true}),durofelStd:num(p.durofelStd,'STD Durofel',{nullable:true}),
    exportPercentage:num(p.exportPercentage,'porcentaje exportacion',{nullable:true}),commercialPercentage:num(p.commercialPercentage,'porcentaje comercial',{nullable:true}),observation:txt(p.observation).slice(0,1000),state:['D','F'].includes(p.state)?p.state:'D',
    damages:damages.map((x)=>({code:int(x.code,'codigo dano',{min:1}),fruits:int(x.fruits,'frutos dano',{min:0})})),
    calibers:calibers.map((x)=>({code:txt(x.code),percentage:num(x.percentage,'porcentaje calibre',{nullable:true}),preCaliber:num(x.preCaliber,'pre calibre',{nullable:true})})).filter(x=>x.code),
    colors:colors.map((x)=>({caliber:txt(x.caliber).slice(0,10),lightRed:num(x.lightRed,'rojo claro',{nullable:true}),darkRed:num(x.darkRed,'rojo oscuro',{nullable:true})})).filter(x=>x.caliber),
    pests:pests.filter(x=>x.selected!==false).map((x)=>({code:int(x.code,'codigo hallazgo',{min:1})}))};
  const exceeds=(value,max)=>value!==null&&value>max;
  const sum=(items,field)=>items.reduce((total,item)=>total+Number(item[field]||0),0);
  if(result.damages.some(x=>exceeds(x.fruits,result.sampleSize))||sum(result.damages,'fruits')>result.sampleSize)throw new CalidadError(400,'SAMPLE_SIZE_EXCEEDED','Los danos no pueden superar el tamano de muestra.');
  if(result.calibers.some(x=>exceeds(x.percentage,100)||exceeds(x.preCaliber,100))||sum(result.calibers,'percentage')!==100||sum(result.calibers,'preCaliber')!==100)throw new CalidadError(400,'PERCENTAGE_TOTAL_INVALID','Calibre y pre calibre deben sumar exactamente 100%.');
  if(result.colors.some(x=>exceeds(x.lightRed,100)||exceeds(x.darkRed,100))||sum(result.colors,'lightRed')!==100||sum(result.colors,'darkRed')!==100)throw new CalidadError(400,'PERCENTAGE_TOTAL_INVALID','Rojo claro y rojo oscuro deben sumar exactamente 100%.');
  if(exceeds(result.durofelFruits,result.sampleSize))throw new CalidadError(400,'SAMPLE_SIZE_EXCEEDED','Los frutos de firmeza no pueden superar el tamano de muestra.');
  if(exceeds(result.exportPercentage,100)||exceeds(result.commercialPercentage,100))throw new CalidadError(400,'PERCENTAGE_EXCEEDED','Los porcentajes de exportacion y comercial no pueden superar 100%.');
  result.qualityPercentage=Math.max(0,Number((100-(sum(result.damages,'fruits')/result.sampleSize*100)).toFixed(2)));
  return result;
};
const bindKey=(r,emp,k)=>r.input('EmpCod',sql.SmallInt,emp).input('TempCod',sql.Char(9),k.tempCod).input('OriCod',sql.SmallInt,k.origin).input('MovTDoc',sql.SmallInt,k.docType).input('MovNGuia',sql.Decimal(10,0),k.guide).input('MovProd',sql.Char(6),k.producer).input('Mov1Nlote',sql.Decimal(10,0),k.lot);
const list=async(emp,q={})=>{const pool=await getPool();const limit=Math.min(Math.max(Number(q.limit)||100,1),500);const r=await pool.request().input('EmpCod',sql.SmallInt,emp).input('Limit',sql.Int,limit).query(`
 SELECT TOP (@Limit) c.CalRecId id,c.CalRecFecha inspectionDate,CONVERT(varchar(8),c.CalRecHora,108) inspectionTime,c.CalRecEstado state,c.TempCod,c.OriCod,c.MovTDoc,c.MovNGuia,RTRIM(c.MovProd) producer,c.Mov1Nlote lot,
 RTRIM(p.ProdNom) producerName,RTRIM(e.EspeNom) speciesName,RTRIM(v.VarNom) varietyName,c.CalRecTamMuestra sampleSize,c.CalRecPorCalidad qualityPercentage,c.CalRecLoginC inspector
 FROM CALRECEP c JOIN MOVFRUT1 d ON d.EmpCod=c.EmpCod AND d.TempCod=c.TempCod AND d.OriCod=c.OriCod AND d.MovTDoc=c.MovTDoc AND d.MovNGuia=c.MovNGuia AND d.MovProd=c.MovProd AND d.Mov1Nlote=c.Mov1Nlote
 LEFT JOIN PRODUCTORES p ON p.EmpCod=c.EmpCod AND p.ProdCod=c.MovProd LEFT JOIN ESPECIES e ON e.EmpCod=c.EmpCod AND e.Especod=c.Especod LEFT JOIN ESPECIES1 v ON v.EmpCod=c.EmpCod AND v.Especod=c.Especod AND v.VarCod=d.Mov1Var
 WHERE c.EmpCod=@EmpCod ORDER BY c.CalRecFecha DESC,c.CalRecHora DESC,c.CalRecId DESC;`);return {data:r.recordset};};
const getOne=async(emp,id,source)=>{const pool=source||await getPool();const req=source instanceof sql.Transaction?new sql.Request(source):pool.request();const r=await req.input('EmpCod',sql.SmallInt,emp).input('Id',sql.BigInt,id).query(`
 SELECT c.*,CONVERT(varchar(8),c.CalRecHora,108) CalRecHoraTexto,RTRIM(p.ProdNom) ProdNom,RTRIM(e.EspeNom) EspeNom,RTRIM(v.VarNom) VarNom,d.Mov1NumE,d.Mov1Cuar,RTRIM(q.CuarNom) CuarNom
 FROM CALRECEP c JOIN MOVFRUT1 d ON d.EmpCod=c.EmpCod AND d.TempCod=c.TempCod AND d.OriCod=c.OriCod AND d.MovTDoc=c.MovTDoc AND d.MovNGuia=c.MovNGuia AND d.MovProd=c.MovProd AND d.Mov1Nlote=c.Mov1Nlote
 LEFT JOIN PRODUCTORES p ON p.EmpCod=c.EmpCod AND p.ProdCod=c.MovProd LEFT JOIN ESPECIES e ON e.EmpCod=c.EmpCod AND e.Especod=c.Especod LEFT JOIN ESPECIES1 v ON v.EmpCod=c.EmpCod AND v.Especod=c.Especod AND v.VarCod=d.Mov1Var LEFT JOIN PRODUCTORES1 q ON q.EmpCod=c.EmpCod AND q.ProdCod=c.MovProd AND q.CuarCod=d.Mov1Cuar
 WHERE c.EmpCod=@EmpCod AND c.CalRecId=@Id;
 SELECT x.MADanCod code,RTRIM(m.MADanDes) label,x.CalDanFrutos fruits FROM CALRECEPDANO x JOIN MAdanos m ON m.EmpCod=x.EmpCod AND m.Especod=x.Especod AND m.MADanCod=x.MADanCod WHERE x.EmpCod=@EmpCod AND x.CalRecId=@Id ORDER BY m.MADanOrden;
 SELECT RTRIM(Calibre) code,CalPorcentaje percentage,CalPreCalibre preCaliber FROM CALRECEPCALIBRE WHERE EmpCod=@EmpCod AND CalRecId=@Id;
 SELECT RTRIM(x.Calibre) caliber,x.CalRojoClaro lightRed,x.CalRojoOscuro darkRed FROM CALRECEPCOLORCALIBRE x WHERE x.EmpCod=@EmpCod AND x.CalRecId=@Id ORDER BY x.Calibre;
 SELECT x.MAPlaCod code,RTRIM(m.MAPlaTipo) type,RTRIM(m.MAPlaDes) label,CAST(1 AS bit) selected FROM CALRECEPPLAGA x JOIN MAPlagas m ON m.EmpCod=x.EmpCod AND m.Especod=x.Especod AND m.MAPlaCod=x.MAPlaCod WHERE x.EmpCod=@EmpCod AND x.CalRecId=@Id ORDER BY m.MAPlaOrden;
 SELECT RTRIM(x.CalColor) color,RTRIM(m.MAColDes) label,x.CalRojoClaro lightRed,x.CalRojoOscuro darkRed FROM CALRECEPCOLOR x JOIN MAColores m ON m.EmpCod=x.EmpCod AND m.Especod=x.Especod AND m.MAColCod=x.CalColor WHERE x.EmpCod=@EmpCod AND x.CalRecId=@Id ORDER BY m.MAColOrden,m.MAColCod;`);
 if(!r.recordsets[0].length)throw new CalidadError(404,'NOT_FOUND','Control de calidad no encontrado.');return {header:r.recordsets[0][0],damages:r.recordsets[1],calibers:r.recordsets[2],colors:r.recordsets[3],pests:r.recordsets[4],legacyColors:r.recordsets[5]};};
const writeDetails=async(tx,emp,id,species,p)=>{const base=()=>new sql.Request(tx).input('EmpCod',sql.SmallInt,emp).input('Id',sql.BigInt,id).input('Especod',sql.SmallInt,species);
 for(const x of p.damages)await base().input('Code',sql.SmallInt,x.code).input('Fruits',sql.Int,x.fruits).query('INSERT CALRECEPDANO VALUES(@EmpCod,@Id,@Especod,@Code,@Fruits)');
 for(const x of p.calibers)await base().input('Code',sql.Char(10),x.code).input('Pct',sql.Decimal(7,2),x.percentage).input('Pre',sql.Decimal(7,2),x.preCaliber).query('INSERT CALRECEPCALIBRE VALUES(@EmpCod,@Id,@Especod,@Code,@Pct,@Pre)');
 for(const x of p.colors)await base().input('Caliber',sql.Char(10),x.caliber).input('Light',sql.Decimal(7,2),x.lightRed).input('Dark',sql.Decimal(7,2),x.darkRed).query('INSERT CALRECEPCOLORCALIBRE(EmpCod,CalRecId,Especod,Calibre,CalRojoClaro,CalRojoOscuro) VALUES(@EmpCod,@Id,@Especod,@Caliber,@Light,@Dark)');
 for(const x of p.pests)await base().input('Code',sql.Int,x.code).query('INSERT CALRECEPPLAGA VALUES(@EmpCod,@Id,@Especod,@Code)');};
const create=async(emp,login,raw)=>{const p=normalize(raw),pool=await getPool(),tx=new sql.Transaction(pool);await tx.begin();try{const found=await bindKey(new sql.Request(tx),emp,p).query('SELECT Mov1Espe FROM MOVFRUT1 WHERE EmpCod=@EmpCod AND TempCod=@TempCod AND OriCod=@OriCod AND MovTDoc=@MovTDoc AND MovNGuia=@MovNGuia AND MovProd=@MovProd AND Mov1Nlote=@Mov1Nlote');if(!found.recordset.length)throw new CalidadError(404,'LOT_NOT_FOUND','El lote no existe.');const species=Number(found.recordset[0].Mov1Espe);const r=await bindKey(new sql.Request(tx),emp,p).input('Species',sql.SmallInt,species).input('Date',sql.Date,p.inspectionDate).input('Time',sql.Time,p.inspectionTime).input('Temp',sql.Decimal(7,2),p.pulpTemperature).input('Sample',sql.Int,p.sampleSize).input('DF',sql.Int,p.durofelFruits).input('DA',sql.Decimal(10,3),p.durofelAverage).input('DS',sql.Decimal(10,3),p.durofelStd).input('Exp',sql.Decimal(7,2),p.exportPercentage).input('Com',sql.Decimal(7,2),p.commercialPercentage).input('Quality',sql.Decimal(7,2),p.qualityPercentage).input('Obs',sql.VarChar(1000),p.observation).input('State',sql.Char(1),p.state).input('Login',sql.Char(10),txt(login).slice(0,10)).query(`INSERT CALRECEP(EmpCod,TempCod,OriCod,MovTDoc,MovNGuia,MovProd,Mov1Nlote,Especod,CalRecFecha,CalRecHora,CalRecTempPulpa,CalRecTamMuestra,CalRecDuroFrutos,CalRecDuroAV,CalRecDuroSTD,CalRecPorExport,CalRecPorComercial,CalRecPorCalidad,CalRecObservacion,CalRecEstado,CalRecLoginC) OUTPUT INSERTED.CalRecId id VALUES(@EmpCod,@TempCod,@OriCod,@MovTDoc,@MovNGuia,@MovProd,@Mov1Nlote,@Species,@Date,@Time,@Temp,@Sample,@DF,@DA,@DS,@Exp,@Com,@Quality,@Obs,@State,@Login)`);const id=r.recordset[0].id;await writeDetails(tx,emp,id,species,p);await tx.commit();return getOne(emp,id);}catch(e){await tx.rollback();throw e;}};
const update=async(emp,login,id,raw)=>{const p=normalize(raw),pool=await getPool(),tx=new sql.Transaction(pool);await tx.begin();try{const current=await getOne(emp,id,tx);if(current.header.CalRecEstado==='A')throw new CalidadError(409,'CONTROL_VOID','No se puede editar un control anulado.');const species=Number(current.header.Especod);await new sql.Request(tx).input('EmpCod',sql.SmallInt,emp).input('Id',sql.BigInt,id).input('Date',sql.Date,p.inspectionDate).input('Time',sql.Time,p.inspectionTime).input('Temp',sql.Decimal(7,2),p.pulpTemperature).input('Sample',sql.Int,p.sampleSize).input('DF',sql.Int,p.durofelFruits).input('DA',sql.Decimal(10,3),p.durofelAverage).input('DS',sql.Decimal(10,3),p.durofelStd).input('Exp',sql.Decimal(7,2),p.exportPercentage).input('Com',sql.Decimal(7,2),p.commercialPercentage).input('Quality',sql.Decimal(7,2),p.qualityPercentage).input('Obs',sql.VarChar(1000),p.observation).input('State',sql.Char(1),p.state).input('Login',sql.Char(10),txt(login).slice(0,10)).query(`UPDATE CALRECEP SET CalRecFecha=@Date,CalRecHora=@Time,CalRecTempPulpa=@Temp,CalRecTamMuestra=@Sample,CalRecDuroFrutos=@DF,CalRecDuroAV=@DA,CalRecDuroSTD=@DS,CalRecPorExport=@Exp,CalRecPorComercial=@Com,CalRecPorCalidad=@Quality,CalRecObservacion=@Obs,CalRecEstado=@State,CalRecLoginUPD=@Login,CalRecFecUPD=GETDATE() WHERE EmpCod=@EmpCod AND CalRecId=@Id;DELETE CALRECEPDANO WHERE EmpCod=@EmpCod AND CalRecId=@Id;DELETE CALRECEPCALIBRE WHERE EmpCod=@EmpCod AND CalRecId=@Id;DELETE CALRECEPCOLORCALIBRE WHERE EmpCod=@EmpCod AND CalRecId=@Id;DELETE CALRECEPPLAGA WHERE EmpCod=@EmpCod AND CalRecId=@Id;`);await writeDetails(tx,emp,id,species,p);await tx.commit();return getOne(emp,id);}catch(e){await tx.rollback();throw e;}};
const remove=async(emp,login,id)=>{const pool=await getPool();const r=await pool.request().input('EmpCod',sql.SmallInt,emp).input('Id',sql.BigInt,id).input('Login',sql.Char(10),txt(login).slice(0,10)).query("UPDATE CALRECEP SET CalRecEstado='A',CalRecLoginUPD=@Login,CalRecFecUPD=GETDATE() WHERE EmpCod=@EmpCod AND CalRecId=@Id AND CalRecEstado<>'A'; SELECT @@ROWCOUNT affected;");if(!r.recordsets[0][0].affected)throw new CalidadError(404,'NOT_FOUND','Control no encontrado o ya anulado.');return {deleted:true};};
const ensureControl=async(pool,emp,id)=>{const r=await pool.request().input('EmpCod',sql.SmallInt,emp).input('Id',sql.BigInt,id).query("SELECT CalRecEstado FROM CALRECEP WHERE EmpCod=@EmpCod AND CalRecId=@Id");if(!r.recordset.length)throw new CalidadError(404,'NOT_FOUND','Control de calidad no encontrado.');return r.recordset[0];};
const listPhotos=async(emp,id)=>{const pool=await getPool();await ensureControl(pool,emp,id);const r=await pool.request().input('EmpCod',sql.SmallInt,emp).input('Id',sql.BigInt,id).query('SELECT CalFotoId id,RTRIM(CalFotoNombre) name,RTRIM(CalFotoMime) mime,CalFotoTamano size,CalFotoOrden sortOrder,CalFotoFecC createdAt FROM CALRECEPFOTO WHERE EmpCod=@EmpCod AND CalRecId=@Id ORDER BY CalFotoOrden,CalFotoId');return {data:r.recordset};};
const addPhotos=async(emp,login,id,files)=>{const pool=await getPool();const control=await ensureControl(pool,emp,id);if(control.CalRecEstado==='A')throw new CalidadError(409,'CONTROL_VOID','No se pueden agregar fotos a un control anulado.');const current=await pool.request().input('EmpCod',sql.SmallInt,emp).input('Id',sql.BigInt,id).query('SELECT COUNT(*) total,COALESCE(MAX(CalFotoOrden),0) maxOrder FROM CALRECEPFOTO WHERE EmpCod=@EmpCod AND CalRecId=@Id');const count=Number(current.recordset[0].total);if(count+files.length>10)throw new CalidadError(400,'PHOTO_LIMIT','El control admite un maximo de 10 fotos.');let order=Number(current.recordset[0].maxOrder);for(const file of files){order+=1;await pool.request().input('EmpCod',sql.SmallInt,emp).input('Id',sql.BigInt,id).input('Name',sql.VarChar(255),txt(file.originalname).slice(0,255)).input('Mime',sql.VarChar(50),file.mimetype).input('Size',sql.Int,file.size).input('Content',sql.VarBinary(sql.MAX),file.buffer).input('Order',sql.SmallInt,order).input('Login',sql.Char(10),txt(login).slice(0,10)).query('INSERT CALRECEPFOTO(EmpCod,CalRecId,CalFotoNombre,CalFotoMime,CalFotoTamano,CalFotoContenido,CalFotoOrden,CalFotoLoginC) VALUES(@EmpCod,@Id,@Name,@Mime,@Size,@Content,@Order,@Login)');}return listPhotos(emp,id);};
const getPhoto=async(emp,id,photoId)=>{const pool=await getPool();const r=await pool.request().input('EmpCod',sql.SmallInt,emp).input('Id',sql.BigInt,id).input('PhotoId',sql.BigInt,photoId).query('SELECT RTRIM(CalFotoNombre) name,RTRIM(CalFotoMime) mime,CalFotoContenido content FROM CALRECEPFOTO WHERE EmpCod=@EmpCod AND CalRecId=@Id AND CalFotoId=@PhotoId');if(!r.recordset.length)throw new CalidadError(404,'PHOTO_NOT_FOUND','Fotografia no encontrada.');return r.recordset[0];};
const removePhoto=async(emp,id,photoId)=>{const pool=await getPool();const control=await ensureControl(pool,emp,id);if(control.CalRecEstado==='A')throw new CalidadError(409,'CONTROL_VOID','No se pueden eliminar fotos de un control anulado.');const r=await pool.request().input('EmpCod',sql.SmallInt,emp).input('Id',sql.BigInt,id).input('PhotoId',sql.BigInt,photoId).query('DELETE FROM CALRECEPFOTO WHERE EmpCod=@EmpCod AND CalRecId=@Id AND CalFotoId=@PhotoId;SELECT @@ROWCOUNT affected;');if(!r.recordsets[0][0].affected)throw new CalidadError(404,'PHOTO_NOT_FOUND','Fotografia no encontrada.');return {deleted:true};};
module.exports={CalidadError,normalize,list,getOne,create,update,remove,listPhotos,addPhotos,getPhoto,removePhoto};
