const { getPool, sql } = require('../conectorMysql/conectorSqlServer');
const { CalidadError } = require('./recepcionesCalidad.service');
const clamp=(v)=>Math.max(0,Math.min(100,Number.isFinite(Number(v))?Number(v):0));
const round=(v,d=1)=>Number(Number(v||0).toFixed(d));
const avg=(rows,field)=>{const values=rows.map(x=>Number(x[field])).filter(Number.isFinite);return values.length?values.reduce((a,b)=>a+b,0)/values.length:0;};
const isoLocal=(d)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const defaultRange=()=>{const today=new Date(),last=new Date(today.getFullYear(),today.getMonth(),0).getDate();return{from:isoLocal(new Date(today.getFullYear(),today.getMonth()-1,Math.min(today.getDate(),last))),to:isoLocal(today)};};
const validDate=(v,label)=>{const x=String(v||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(x))throw new CalidadError(400,'VALIDATION_ERROR',`${label} no es valida.`);return x;};
const aggregate=(rows,labelField,valueFields)=>{const map=new Map();rows.forEach(row=>{const label=String(row[labelField]||'').trim();const item=map.get(label)||{label,count:0};valueFields.forEach(field=>item[field]=(item[field]||0)+Number(row[field]||0));if(row.displayOrder!=null)item.displayOrder=Math.min(item.displayOrder??32767,Number(row.displayOrder)||32767);item.count++;map.set(label,item);});return[...map.values()];};
const buildQualityClassification=(sampleTotal,damageTotal)=>{const sample=Math.max(0,Number(sampleTotal)||0),damaged=Math.min(sample,Math.max(0,Number(damageTotal)||0)),damagePct=sample?round(damaged/sample*100):0;return[{label:'Fruta sin daño',value:round(100-damagePct),fruits:sample-damaged},{label:'Fruta con daño',value:damagePct,fruits:damaged}];};
const byDisplayOrder=(left,right)=>Number(left.displayOrder??32767)-Number(right.displayOrder??32767)||left.index-right.index;
const buildCaliberDistribution=(rows)=>aggregate(rows,'label',['percentage','preCaliber']).map((x,index)=>({label:x.label,caliber:round(x.percentage,0),preCaliber:round(x.preCaliber,0),total:round(x.percentage+x.preCaliber,0),displayOrder:x.displayOrder,index})).sort(byDisplayOrder).map(({displayOrder,index,...item})=>item);
const buildColorDistribution=(rows)=>aggregate(rows,'label',['lightRed','darkRed']).map((x,index)=>({label:x.label,lightRed:round(x.lightRed,0),darkRed:round(x.darkRed,0),total:round(x.lightRed+x.darkRed,0),displayOrder:x.displayOrder,index})).sort(byDisplayOrder).map(({displayOrder,index,...item})=>item);
const buildObservations=(controls)=>controls.map(control=>({controlId:control.id,lot:Number(control.lot),inspectionDate:control.inspectionDate,producer:String(control.producer||'').trim(),species:String(control.species||'').trim(),variety:String(control.variety||'').trim(),text:String(control.observation||'').trim()})).filter(item=>item.text);

const getDashboard=async(empCod,input={})=>{
 const defaults=defaultRange(),from=validDate(input.from||defaults.from,'Fecha desde'),to=validDate(input.to||defaults.to,'Fecha hasta');
 if(from>to)throw new CalidadError(400,'VALIDATION_ERROR','La fecha desde no puede superar la fecha hasta.');
 const lot=input.lot==null||input.lot===''?null:Number(input.lot);if(lot!==null&&(!Number.isInteger(lot)||lot<=0))throw new CalidadError(400,'VALIDATION_ERROR','El lote no es valido.');
 const pool=await getPool();const result=await pool.request().input('EmpCod',sql.SmallInt,empCod).input('From',sql.Date,from).input('To',sql.Date,to).input('Lot',sql.Decimal(10,0),lot).query(`
 SELECT c.CalRecId id,c.Mov1Nlote lot,c.CalRecFecha inspectionDate,c.CalRecTamMuestra sampleSize,c.CalRecDuroAV firmness,c.CalRecPorExport exportPct,c.CalRecPorComercial commercialPct,c.CalRecObservacion observation,h.MovGBrik brix,RTRIM(p.ProdNom) producer,RTRIM(e.EspeNom) species,RTRIM(v.VarNom) variety
 FROM CALRECEP c JOIN MOVFRUT h ON h.EmpCod=c.EmpCod AND h.TempCod=c.TempCod AND h.OriCod=c.OriCod AND h.MovTDoc=c.MovTDoc AND h.MovNGuia=c.MovNGuia AND h.MovProd=c.MovProd JOIN MOVFRUT1 d ON d.EmpCod=c.EmpCod AND d.TempCod=c.TempCod AND d.OriCod=c.OriCod AND d.MovTDoc=c.MovTDoc AND d.MovNGuia=c.MovNGuia AND d.MovProd=c.MovProd AND d.Mov1Nlote=c.Mov1Nlote LEFT JOIN PRODUCTORES p ON p.EmpCod=c.EmpCod AND p.ProdCod=c.MovProd LEFT JOIN ESPECIES e ON e.EmpCod=c.EmpCod AND e.Especod=c.Especod LEFT JOIN ESPECIES1 v ON v.EmpCod=c.EmpCod AND v.Especod=c.Especod AND v.VarCod=d.Mov1Var
 WHERE c.EmpCod=@EmpCod AND c.CalRecEstado='F' AND c.CalRecFecha>=@From AND c.CalRecFecha<DATEADD(day,1,@To) AND (@Lot IS NULL OR c.Mov1Nlote=@Lot);
 SELECT d.CalRecId controlId,RTRIM(m.MADanDes) label,d.CalDanFrutos fruits FROM CALRECEPDANO d JOIN CALRECEP c ON c.EmpCod=d.EmpCod AND c.CalRecId=d.CalRecId JOIN MAdanos m ON m.EmpCod=d.EmpCod AND m.Especod=d.Especod AND m.MADanCod=d.MADanCod WHERE c.EmpCod=@EmpCod AND c.CalRecEstado='F' AND c.CalRecFecha>=@From AND c.CalRecFecha<DATEADD(day,1,@To) AND (@Lot IS NULL OR c.Mov1Nlote=@Lot);
 SELECT d.CalRecId controlId,RTRIM(d.Calibre) label,d.CalPorcentaje percentage,d.CalPreCalibre preCaliber,COALESCE(m.CalOrden,m.CalCod,32767) displayOrder FROM CALRECEPCALIBRE d JOIN CALRECEP c ON c.EmpCod=d.EmpCod AND c.CalRecId=d.CalRecId LEFT JOIN CALIBRES m ON m.EmpCod=d.EmpCod AND m.Especod=d.Especod AND m.Calibre=d.Calibre WHERE c.EmpCod=@EmpCod AND c.CalRecEstado='F' AND c.CalRecFecha>=@From AND c.CalRecFecha<DATEADD(day,1,@To) AND (@Lot IS NULL OR c.Mov1Nlote=@Lot);
 SELECT d.CalRecId controlId,RTRIM(d.Calibre) label,d.CalRojoClaro lightRed,d.CalRojoOscuro darkRed,COALESCE(m.CalOrden,m.CalCod,32767) displayOrder FROM CALRECEPCOLORCALIBRE d JOIN CALRECEP c ON c.EmpCod=d.EmpCod AND c.CalRecId=d.CalRecId LEFT JOIN CALIBRES m ON m.EmpCod=d.EmpCod AND m.Especod=d.Especod AND m.Calibre=d.Calibre WHERE c.EmpCod=@EmpCod AND c.CalRecEstado='F' AND c.CalRecFecha>=@From AND c.CalRecFecha<DATEADD(day,1,@To) AND (@Lot IS NULL OR c.Mov1Nlote=@Lot);
 SELECT d.CalRecId controlId,RTRIM(m.MAPlaTipo) type,RTRIM(m.MAPlaDes) label FROM CALRECEPPLAGA d JOIN CALRECEP c ON c.EmpCod=d.EmpCod AND c.CalRecId=d.CalRecId JOIN MAPlagas m ON m.EmpCod=d.EmpCod AND m.Especod=d.Especod AND m.MAPlaCod=d.MAPlaCod WHERE c.EmpCod=@EmpCod AND c.CalRecEstado='F' AND c.CalRecFecha>=@From AND c.CalRecFecha<DATEADD(day,1,@To) AND (@Lot IS NULL OR c.Mov1Nlote=@Lot);
 SELECT f.CalRecId controlId,f.CalFotoId id,RTRIM(f.CalFotoNombre) name,RTRIM(f.CalFotoMime) mime,f.CalFotoOrden sortOrder
 FROM CALRECEPFOTO f JOIN CALRECEP c ON c.EmpCod=f.EmpCod AND c.CalRecId=f.CalRecId
 WHERE c.EmpCod=@EmpCod AND c.CalRecEstado='F' AND c.CalRecFecha>=@From AND c.CalRecFecha<DATEADD(day,1,@To) AND (@Lot IS NULL OR c.Mov1Nlote=@Lot)
 ORDER BY c.Mov1Nlote,f.CalFotoOrden,f.CalFotoId;
 SELECT c.CalRecId id,c.Mov1Nlote lot,RTRIM(p.ProdNom) producer,RTRIM(e.EspeNom) species,RTRIM(v.VarNom) variety
 FROM CALRECEP c
 JOIN MOVFRUT1 d ON d.EmpCod=c.EmpCod AND d.TempCod=c.TempCod AND d.OriCod=c.OriCod AND d.MovTDoc=c.MovTDoc AND d.MovNGuia=c.MovNGuia AND d.MovProd=c.MovProd AND d.Mov1Nlote=c.Mov1Nlote
 LEFT JOIN PRODUCTORES p ON p.EmpCod=c.EmpCod AND p.ProdCod=c.MovProd
 LEFT JOIN ESPECIES e ON e.EmpCod=c.EmpCod AND e.Especod=c.Especod
 LEFT JOIN ESPECIES1 v ON v.EmpCod=c.EmpCod AND v.Especod=c.Especod AND v.VarCod=d.Mov1Var
 WHERE c.EmpCod=@EmpCod AND c.CalRecEstado='F' AND c.CalRecFecha>=@From AND c.CalRecFecha<DATEADD(day,1,@To)
 ORDER BY c.Mov1Nlote;
 SELECT COALESCE(SUM(c.CalRecTamMuestra),0) sampleTotal,COALESCE(SUM(COALESCE(d.damageTotal,0)),0) damageTotal
 FROM CALRECEP c
 OUTER APPLY(SELECT SUM(x.CalDanFrutos) damageTotal FROM CALRECEPDANO x WHERE x.EmpCod=c.EmpCod AND x.CalRecId=c.CalRecId)d
 WHERE c.EmpCod=@EmpCod AND c.CalRecEstado='F' AND c.CalRecFecha>=@From AND c.CalRecFecha<DATEADD(day,1,@To);`);
 const [controls,damages,calibers,colors,pests,photos,availableLots,historyRows]=result.recordsets,sampleTotal=controls.reduce((s,x)=>s+Number(x.sampleSize||0),0),damageTotal=damages.reduce((s,x)=>s+Number(x.fruits||0),0);
 const classification=buildQualityClassification(sampleTotal,damageTotal),exportFruit=classification[0].value,commercial=classification[1].value,history=historyRows[0]||{},historicalClassification=buildQualityClassification(history.sampleTotal,history.damageTotal),projectedYield=historicalClassification[0].value,firmnessValue=avg(controls,'firmness'),firmness=clamp(firmnessValue/70*100),brixValue=avg(controls,'brix'),brix=clamp(brixValue/20*100),defectFree=exportFruit,sanitary=controls.length?clamp(100-pests.length/controls.length*25):0;
 const colorDistribution=buildColorDistribution(colors);
 const virusLots=new Set(pests.filter(x=>String(x.type).trim()==='VIRUS').map(x=>String(x.controlId))).size,virusLotPct=controls.length?clamp(virusLots/controls.length*100):0;
 const caliberDistribution=buildCaliberDistribution(calibers);
 const defectDistribution=aggregate(damages,'label',['fruits']).map(x=>({label:x.label,fruits:x.fruits,percentage:round(sampleTotal?x.fruits/sampleTotal*100:0)})).sort((a,b)=>b.fruits-a.fruits);
 const pestMap=new Map();pests.forEach(x=>{const key=`${x.type}|${x.label}`,item=pestMap.get(key)||{type:x.type,label:x.label,count:0};item.count++;pestMap.set(key,item);});const pestDistribution=[...pestMap.values()].sort((a,b)=>b.count-a.count);
 const top=defectDistribution[0],conclusion=!controls.length?'No existen controles finalizados para los filtros seleccionados.':`La selección presenta ${exportFruit}% de fruta exportación y ${commercial}% de fruta comercial. ${top?`El principal defecto es ${top.label} con ${top.percentage}%.`:'No se registran daños.'} ${pests.length?`Se detectaron ${pests.length} hallazgos sanitarios.`:'Sin hallazgos sanitarios.'}`;
 const quickConclusions=[{title:'Fruta exportación',value:`${exportFruit}%`,tone:exportFruit>=80?'success':exportFruit>=60?'warning':'error',text:`Fruta comercial ${commercial}%`},{title:'Principal defecto',value:top?`${top.percentage}%`:'0%',tone:top&&top.percentage>10?'error':'success',text:top?.label||'Sin daños'},{title:'Condición sanitaria',value:`${round(sanitary)}%`,tone:sanitary>=80?'success':sanitary>=60?'warning':'error',text:pests.length?`${pests.length} hallazgos`:'Sin hallazgos'},{title:'Lotes con virus',value:`${round(virusLotPct)}%`,tone:virusLotPct===0?'success':'error',text:virusLots?`${virusLots} lote(s) afectados`:'Sin virus'}];
 const soundPct=exportFruit,damagePct=commercial,dominantColor=[...colorDistribution].sort((a,b)=>b.total-a.total)[0],dominantCaliber=[...caliberDistribution].sort((a,b)=>b.total-a.total)[0];
 const chartConclusions={classification:controls.length?`De ${sampleTotal} frutos muestreados, ${classification[0].fruits} no presentan daño y ${classification[1].fruits} registran daño. La segregación corresponde a ${soundPct}% de fruta sin daño y ${damagePct}% con daño.`:'No hay controles finalizados para analizar la segregación.',color:dominantColor?`El calibre con mayor medición de color es ${dominantColor.label}, con ${dominantColor.total} frutos: ${dominantColor.lightRed} rojo claro y ${dominantColor.darkRed} rojo oscuro.`:'No existen mediciones de color por calibre en el período seleccionado.',caliber:dominantCaliber?`El calibre con mayor cantidad registrada es ${dominantCaliber.label}, con ${dominantCaliber.total} frutos entre calibre (${dominantCaliber.caliber}) y pre calibre (${dominantCaliber.preCaliber}).`:'No existen mediciones de calibre en el período seleccionado.',defects:top?`${top.label} es el defecto de mayor incidencia, con ${top.fruits} frutos y ${top.percentage}% de la muestra total. ${top.percentage>10?'Requiere acción correctiva y seguimiento por productor y lote.':'La incidencia se mantiene acotada, aunque debe vigilarse su evolución.'}`:'No se registran daños ni defectos en las muestras analizadas.'};
 const generalConclusion=!controls.length?'No existen controles finalizados para el período y lote seleccionados; todavía no hay base suficiente para emitir una conclusión comercial o sanitaria.':`El conjunto analizado comprende ${controls.length} control(es) de calidad. La selección actual clasifica ${exportFruit}% como fruta exportación y ${commercial}% como fruta comercial; ambas categorías completan el 100% de la muestra. El rendimiento proyectado histórico del período es ${round(projectedYield)}%, calculado de forma ponderada sobre ${Number(history.sampleTotal||0)} frutos muestreados. La firmeza promedio es ${round(firmnessValue)} AV y el Brix promedio ${round(brixValue)} °Bx. ${top?`El principal riesgo de calidad es ${top.label} (${top.percentage}% de la muestra).`:'No aparecen defectos relevantes en las muestras.'} ${pests.length?`Se contabilizan ${pests.length} hallazgo(s) sanitario(s) y ${round(virusLotPct)}% de los lotes presenta virus, por lo que corresponde revisar trazabilidad, productor y cuartel antes de definir el destino.`:'No se registran plagas, virus ni dípteros, condición favorable para continuidad operacional.'}`;
 const photosByControl=new Map();photos.forEach(photo=>{const id=String(photo.controlId),items=photosByControl.get(id)||[];items.push({id:photo.id,name:photo.name,mime:photo.mime,sortOrder:photo.sortOrder});photosByControl.set(id,items);});
 const photoLots=controls.map(control=>({controlId:control.id,lot:Number(control.lot),producer:control.producer,species:control.species,variety:control.variety,photos:photosByControl.get(String(control.id))||[]})).filter(item=>item.photos.length);
 return{filters:{from,to,lot},lots:availableLots.map(x=>({id:x.id,lot:Number(x.lot),producer:x.producer,species:x.species,variety:x.variety})),indicators:{projectedYield:round(projectedYield),historicalSampleSize:Number(history.sampleTotal||0),exportFruit:round(exportFruit),commercial:round(commercial),firmness:round(firmness),firmnessValue:round(firmnessValue),brix:round(brix),brixValue:round(brixValue),defectFree:round(defectFree),sanitary:round(sanitary),virusLotPct:round(virusLotPct)},classification,colorDistribution,caliberDistribution,defectDistribution,pestDistribution,photoLots,observations:buildObservations(controls),quickConclusions,chartConclusions,generalConclusion,conclusion,methodology:'Rendimiento proyectado ponderado sobre el histórico de muestras del período. Exportación y comercial se calculan sobre la selección actual y siempre completan 100%.'};
};
module.exports={getDashboard,defaultRange,buildQualityClassification,buildCaliberDistribution,buildColorDistribution,buildObservations};
