const { getPool, sql } = require('../conectorMysql/conectorSqlServer');
const { CalidadError } = require('./recepcionesCalidad.service');
const clamp=(v)=>Math.max(0,Math.min(100,Number.isFinite(Number(v))?Number(v):0));
const round=(v,d=1)=>Number(Number(v||0).toFixed(d));
const avg=(rows,field)=>{const values=rows.map(x=>Number(x[field])).filter(Number.isFinite);return values.length?values.reduce((a,b)=>a+b,0)/values.length:0;};
const isoLocal=(d)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const defaultRange=()=>{const today=new Date(),last=new Date(today.getFullYear(),today.getMonth(),0).getDate();return{from:isoLocal(new Date(today.getFullYear(),today.getMonth()-1,Math.min(today.getDate(),last))),to:isoLocal(today)};};
const validDate=(v,label)=>{const x=String(v||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(x))throw new CalidadError(400,'VALIDATION_ERROR',`${label} no es valida.`);return x;};
const aggregate=(rows,labelField,valueFields)=>{const map=new Map();rows.forEach(row=>{const label=String(row[labelField]||'').trim();const item=map.get(label)||{label,count:0};valueFields.forEach(field=>item[field]=(item[field]||0)+Number(row[field]||0));item.count++;map.set(label,item);});return[...map.values()];};

const getDashboard=async(empCod,input={})=>{
 const defaults=defaultRange(),from=validDate(input.from||defaults.from,'Fecha desde'),to=validDate(input.to||defaults.to,'Fecha hasta');
 if(from>to)throw new CalidadError(400,'VALIDATION_ERROR','La fecha desde no puede superar la fecha hasta.');
 const lot=input.lot==null||input.lot===''?null:Number(input.lot);if(lot!==null&&(!Number.isInteger(lot)||lot<=0))throw new CalidadError(400,'VALIDATION_ERROR','El lote no es valido.');
 const pool=await getPool();const result=await pool.request().input('EmpCod',sql.SmallInt,empCod).input('From',sql.Date,from).input('To',sql.Date,to).input('Lot',sql.Decimal(10,0),lot).query(`
 SELECT c.CalRecId id,c.Mov1Nlote lot,c.CalRecFecha inspectionDate,c.CalRecTamMuestra sampleSize,c.CalRecDuroAV firmness,c.CalRecPorExport exportPct,c.CalRecPorComercial commercialPct,c.CalRecObservacion observation,h.MovGBrik brix,RTRIM(p.ProdNom) producer,RTRIM(e.EspeNom) species,RTRIM(v.VarNom) variety
 FROM CALRECEP c JOIN MOVFRUT h ON h.EmpCod=c.EmpCod AND h.TempCod=c.TempCod AND h.OriCod=c.OriCod AND h.MovTDoc=c.MovTDoc AND h.MovNGuia=c.MovNGuia AND h.MovProd=c.MovProd JOIN MOVFRUT1 d ON d.EmpCod=c.EmpCod AND d.TempCod=c.TempCod AND d.OriCod=c.OriCod AND d.MovTDoc=c.MovTDoc AND d.MovNGuia=c.MovNGuia AND d.MovProd=c.MovProd AND d.Mov1Nlote=c.Mov1Nlote LEFT JOIN PRODUCTORES p ON p.EmpCod=c.EmpCod AND p.ProdCod=c.MovProd LEFT JOIN ESPECIES e ON e.EmpCod=c.EmpCod AND e.Especod=c.Especod LEFT JOIN ESPECIES1 v ON v.EmpCod=c.EmpCod AND v.Especod=c.Especod AND v.VarCod=d.Mov1Var
 WHERE c.EmpCod=@EmpCod AND c.CalRecEstado='F' AND c.CalRecFecha>=@From AND c.CalRecFecha<DATEADD(day,1,@To) AND (@Lot IS NULL OR c.Mov1Nlote=@Lot);
 SELECT d.CalRecId controlId,RTRIM(m.MADanDes) label,d.CalDanFrutos fruits FROM CALRECEPDANO d JOIN CALRECEP c ON c.EmpCod=d.EmpCod AND c.CalRecId=d.CalRecId JOIN MAdanos m ON m.EmpCod=d.EmpCod AND m.Especod=d.Especod AND m.MADanCod=d.MADanCod WHERE c.EmpCod=@EmpCod AND c.CalRecEstado='F' AND c.CalRecFecha>=@From AND c.CalRecFecha<DATEADD(day,1,@To) AND (@Lot IS NULL OR c.Mov1Nlote=@Lot);
 SELECT d.CalRecId controlId,RTRIM(d.Calibre) label,d.CalPorcentaje percentage,d.CalPreCalibre preCaliber FROM CALRECEPCALIBRE d JOIN CALRECEP c ON c.EmpCod=d.EmpCod AND c.CalRecId=d.CalRecId WHERE c.EmpCod=@EmpCod AND c.CalRecEstado='F' AND c.CalRecFecha>=@From AND c.CalRecFecha<DATEADD(day,1,@To) AND (@Lot IS NULL OR c.Mov1Nlote=@Lot);
 SELECT d.CalRecId controlId,RTRIM(d.Calibre) label,d.CalRojoClaro lightRed,d.CalRojoOscuro darkRed FROM CALRECEPCOLORCALIBRE d JOIN CALRECEP c ON c.EmpCod=d.EmpCod AND c.CalRecId=d.CalRecId WHERE c.EmpCod=@EmpCod AND c.CalRecEstado='F' AND c.CalRecFecha>=@From AND c.CalRecFecha<DATEADD(day,1,@To) AND (@Lot IS NULL OR c.Mov1Nlote=@Lot)
 UNION ALL
 SELECT d.CalRecId controlId,CONCAT('Historico ',RTRIM(m.MAColDes)) label,d.CalRojoClaro lightRed,d.CalRojoOscuro darkRed FROM CALRECEPCOLOR d JOIN CALRECEP c ON c.EmpCod=d.EmpCod AND c.CalRecId=d.CalRecId JOIN MAColores m ON m.EmpCod=d.EmpCod AND m.Especod=d.Especod AND m.MAColCod=d.CalColor WHERE c.EmpCod=@EmpCod AND c.CalRecEstado='F' AND c.CalRecFecha>=@From AND c.CalRecFecha<DATEADD(day,1,@To) AND (@Lot IS NULL OR c.Mov1Nlote=@Lot);
 SELECT d.CalRecId controlId,RTRIM(m.MAPlaTipo) type,RTRIM(m.MAPlaDes) label FROM CALRECEPPLAGA d JOIN CALRECEP c ON c.EmpCod=d.EmpCod AND c.CalRecId=d.CalRecId JOIN MAPlagas m ON m.EmpCod=d.EmpCod AND m.Especod=d.Especod AND m.MAPlaCod=d.MAPlaCod WHERE c.EmpCod=@EmpCod AND c.CalRecEstado='F' AND c.CalRecFecha>=@From AND c.CalRecFecha<DATEADD(day,1,@To) AND (@Lot IS NULL OR c.Mov1Nlote=@Lot);
 SELECT f.CalRecId controlId,f.CalFotoId id,RTRIM(f.CalFotoNombre) name,RTRIM(f.CalFotoMime) mime,f.CalFotoOrden sortOrder
 FROM CALRECEPFOTO f JOIN CALRECEP c ON c.EmpCod=f.EmpCod AND c.CalRecId=f.CalRecId
 WHERE c.EmpCod=@EmpCod AND c.CalRecEstado='F' AND c.CalRecFecha>=@From AND c.CalRecFecha<DATEADD(day,1,@To) AND (@Lot IS NULL OR c.Mov1Nlote=@Lot)
 ORDER BY c.Mov1Nlote,f.CalFotoOrden,f.CalFotoId;`);
 const [controls,damages,calibers,colors,pests,photos]=result.recordsets,sampleTotal=controls.reduce((s,x)=>s+Number(x.sampleSize||0),0),damageTotal=damages.reduce((s,x)=>s+Number(x.fruits||0),0);
 const projectedYield=clamp(avg(controls,'exportPct')),commercial=clamp(avg(controls,'commercialPct')),firmnessValue=avg(controls,'firmness'),firmness=clamp(firmnessValue/70*100),brixValue=avg(controls,'brix'),brix=clamp(brixValue/20*100),defectFree=clamp(100-(sampleTotal?damageTotal/sampleTotal*100:0)),sanitary=controls.length?clamp(100-pests.length/controls.length*25):0;
 const colorDistribution=aggregate(colors,'label',['lightRed','darkRed']).map(x=>({label:x.label,lightRed:round(x.lightRed/x.count),darkRed:round(x.darkRed/x.count)}));const colorTotal=colorDistribution.reduce((s,x)=>s+x.lightRed+x.darkRed,0),colorAccepted=colorDistribution.reduce((s,x)=>s+x.darkRed,0),color=clamp(colorTotal?colorAccepted/colorTotal*100:0);
 const virusLots=new Set(pests.filter(x=>String(x.type).trim()==='VIRUS').map(x=>String(x.controlId))).size,virusLotPct=controls.length?clamp(virusLots/controls.length*100):0;
 const approval=round(projectedYield*.35+firmness*.20+brix*.15+defectFree*.15+color*.10+sanitary*.05);
 const caliberDistribution=aggregate(calibers,'label',['percentage','preCaliber']).map(x=>({label:x.label,percentage:round(x.percentage/x.count),preCaliber:round(x.preCaliber/x.count)}));
 const defectDistribution=aggregate(damages,'label',['fruits']).map(x=>({label:x.label,fruits:x.fruits,percentage:round(sampleTotal?x.fruits/sampleTotal*100:0)})).sort((a,b)=>b.fruits-a.fruits);
 const pestMap=new Map();pests.forEach(x=>{const key=`${x.type}|${x.label}`,item=pestMap.get(key)||{type:x.type,label:x.label,count:0};item.count++;pestMap.set(key,item);});const pestDistribution=[...pestMap.values()].sort((a,b)=>b.count-a.count);
 const premium=controls.filter(c=>{const damage=damages.filter(x=>String(x.controlId)===String(c.id)).reduce((s,x)=>s+Number(x.fruits||0),0),findings=pests.filter(x=>String(x.controlId)===String(c.id)).length;return Number(c.exportPct||0)>=70&&clamp(Number(c.firmness||0)/70*100)>=70&&clamp(Number(c.brix||0)/20*100)>=70&&(Number(c.sampleSize)?damage/Number(c.sampleSize)*100:100)<=10&&findings===0;}).length;
 const top=defectDistribution[0],conclusion=!controls.length?'No existen controles finalizados para los filtros seleccionados.':`${approval>=80?'Desempeño favorable':approval>=60?'Desempeño aceptable con observaciones':'Desempeño bajo la meta'} (${approval}/100). ${top?`El principal defecto es ${top.label} con ${top.percentage}%.`:'No se registran daños.'} ${pests.length?`Se detectaron ${pests.length} hallazgos sanitarios.`:'Sin hallazgos sanitarios.'}`;
 const quickConclusions=[{title:'Resultado general',value:`${approval}/100`,tone:approval>=80?'success':approval>=60?'warning':'error',text:approval>=80?'Desempeño favorable':approval>=60?'Aceptable con observaciones':'Bajo la meta'},{title:'Principal defecto',value:top?`${top.percentage}%`:'0%',tone:top&&top.percentage>10?'error':'success',text:top?.label||'Sin daños'},{title:'Condición sanitaria',value:`${round(sanitary)}%`,tone:sanitary>=80?'success':sanitary>=60?'warning':'error',text:pests.length?`${pests.length} hallazgos`:'Sin hallazgos'},{title:'Lotes con virus',value:`${round(virusLotPct)}%`,tone:virusLotPct===0?'success':'error',text:virusLots?`${virusLots} lote(s) afectados`:'Sin virus'}];
 const premiumPct=controls.length?round(premium/controls.length*100):0,dominantColor=[...colorDistribution].sort((a,b)=>(b.lightRed+b.darkRed)-(a.lightRed+a.darkRed))[0],dominantCaliber=[...caliberDistribution].sort((a,b)=>b.percentage-a.percentage)[0];
 const chartConclusions={classification:controls.length?`${premiumPct}% de los lotes evaluados clasifica como premium (${premium} de ${controls.length}). ${premiumPct>=70?'La composición es favorable para programas de mayor valor.':'Conviene revisar las brechas que desplazan fruta fuera de la categoría premium.'}`:'No hay controles finalizados para analizar la segregación.',color:dominantColor?`El calibre con mayor medición de color es ${dominantColor.label}, con ${round(dominantColor.lightRed+dominantColor.darkRed)} frutos combinados. El ${round(color)}% de la medición corresponde a rojo oscuro.`:'No existen mediciones de color por calibre en el período seleccionado.',caliber:dominantCaliber?`El calibre con mayor participación es ${dominantCaliber.label}, con ${dominantCaliber.percentage}%. Esta concentración permite anticipar el mix comercial y orientar la selección de embalajes.`:'No existen mediciones de calibre en el período seleccionado.',defects:top?`${top.label} es el defecto de mayor incidencia, con ${top.fruits} frutos y ${top.percentage}% de la muestra total. ${top.percentage>10?'Requiere acción correctiva y seguimiento por productor y lote.':'La incidencia se mantiene acotada, aunque debe vigilarse su evolución.'}`:'No se registran daños ni defectos en las muestras analizadas.'};
 const generalConclusion=!controls.length?'No existen controles finalizados para el período y lote seleccionados; todavía no hay base suficiente para emitir una conclusión comercial o sanitaria.':`El conjunto analizado comprende ${controls.length} control(es) de calidad y alcanza una aprobación global de ${approval}/100. El rendimiento exportable proyectado es ${round(projectedYield)}%, con firmeza promedio de ${round(firmnessValue)} AV y Brix promedio de ${round(brixValue)} °Bx; en conjunto, estos indicadores describen la aptitud esperada de la fruta para proceso, conservación y destino comercial. La segregación identifica ${premiumPct}% de lotes premium, mientras la ausencia de defectos llega a ${round(defectFree)}% y la condición sanitaria a ${round(sanitary)}%. ${top?`El principal riesgo de calidad es ${top.label} (${top.percentage}% de la muestra).`:'No aparecen defectos relevantes en las muestras.'} ${pests.length?`Se contabilizan ${pests.length} hallazgo(s) sanitario(s) y ${round(virusLotPct)}% de los lotes presenta virus, por lo que corresponde revisar trazabilidad, productor y cuartel antes de definir el destino.`:'No se registran plagas, virus ni dípteros, condición favorable para continuidad operacional.'} Desde el punto de vista del negocio, ${approval>=80?'el resultado respalda una recepción favorable y una proyección comercial sólida, manteniendo monitoreo sobre las variables dominantes.':approval>=60?'la fruta puede continuar con observaciones, priorizando control de defectos, condición sanitaria y consistencia de firmeza y calibre antes de comprometer programas premium.':'el resultado está bajo la meta y aconseja contener la asignación premium, reforzar inspección y acordar acciones correctivas con el origen antes de avanzar.'}`;
 const photosByControl=new Map();photos.forEach(photo=>{const id=String(photo.controlId),items=photosByControl.get(id)||[];items.push({id:photo.id,name:photo.name,mime:photo.mime,sortOrder:photo.sortOrder});photosByControl.set(id,items);});
 const photoLots=controls.map(control=>({controlId:control.id,lot:Number(control.lot),producer:control.producer,species:control.species,variety:control.variety,photos:photosByControl.get(String(control.id))||[]})).filter(item=>item.photos.length);
 return{filters:{from,to,lot},lots:controls.map(x=>({id:x.id,lot:Number(x.lot),producer:x.producer,species:x.species,variety:x.variety})),indicators:{projectedYield:round(projectedYield),commercial:round(commercial),firmness:round(firmness),firmnessValue:round(firmnessValue),brix:round(brix),brixValue:round(brixValue),defectFree:round(defectFree),sanitary:round(sanitary),virusLotPct:round(virusLotPct),approval},classification:[{label:'Premium',value:premium},{label:'No premium',value:controls.length-premium}],colorDistribution,caliberDistribution,defectDistribution,pestDistribution,photoLots,observations:controls.map(x=>String(x.observation||'').trim()).filter(Boolean),quickConclusions,chartConclusions,generalConclusion,conclusion,methodology:'Indicadores preliminares: firmeza normalizada contra 70 AV, Brix contra 20 y aprobación ponderada 35/20/15/15/10/5.'};
};
module.exports={getDashboard,defaultRange};
