SET NOCOUNT ON;
SET XACT_ABORT ON;

IF OBJECT_ID(N'dbo.FOLIOSPROC', N'U') IS NULL
  THROW 50090, 'No existe dbo.FOLIOSPROC; aplique primero la migracion de Ingreso de Tarjas.', 1;

BEGIN TRANSACTION;

IF COL_LENGTH(N'dbo.FOLIOSPROC', N'DestCod') IS NULL
  ALTER TABLE dbo.FOLIOSPROC ADD DestCod smallint NULL;

IF COL_LENGTH(N'dbo.FOLIOSPROC', N'FPNCaja') IS NULL
  ALTER TABLE dbo.FOLIOSPROC ADD FPNCaja decimal(10,0) NULL;

IF COL_LENGTH(N'dbo.FOLIOSPROC', N'FPServicio') IS NULL
  ALTER TABLE dbo.FOLIOSPROC ADD FPServicio varchar(30) NULL;

COMMIT TRANSACTION;

SELECT
  COL_LENGTH(N'dbo.FOLIOSPROC', N'DestCod') AS DestCodBytes,
  COL_LENGTH(N'dbo.FOLIOSPROC', N'FPNCaja') AS FPNCajaBytes,
  COL_LENGTH(N'dbo.FOLIOSPROC', N'FPServicio') AS FPServicioBytes;
