SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF OBJECT_ID('dbo.CALRECEPCOLORCALIBRE', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.CALRECEPCOLORCALIBRE (
    EmpCod smallint NOT NULL,
    CalRecId bigint NOT NULL,
    Especod smallint NOT NULL,
    Calibre char(10) NOT NULL,
    CalRojoClaro decimal(7,2) NULL,
    CalRojoOscuro decimal(7,2) NULL,
    CONSTRAINT PK_CALRECEPCOLORCALIBRE PRIMARY KEY (EmpCod,CalRecId,Calibre),
    CONSTRAINT FK_CALRECEPCOLORCALIBRE_Control FOREIGN KEY (EmpCod,CalRecId)
      REFERENCES dbo.CALRECEP(EmpCod,CalRecId) ON DELETE CASCADE,
    CONSTRAINT CK_CALRECEPCOLORCALIBRE_Claro CHECK (CalRojoClaro IS NULL OR CalRojoClaro >= 0),
    CONSTRAINT CK_CALRECEPCOLORCALIBRE_Oscuro CHECK (CalRojoOscuro IS NULL OR CalRojoOscuro >= 0)
  );
END;

COMMIT TRANSACTION;
