const router=require('express').Router(); const auth=require('../../middleware/authContext'); const {requirePermission,requireAnyPermission}=require('../../middleware/securityAuthorization'); const s=require('./capturaCajas.service');
const run=(fn)=>async(req,res,next)=>{try{res.json(await fn(req,res));}catch(e){if(e instanceof s.CapturaCajasError)return res.status(e.status).json({code:e.code,message:e.message});next(e);}};
const orderAdmPermission=Object.freeze({sistema:110,modulo:2,programa:2});
const readPermission=requireAnyPermission([s.permission,orderAdmPermission]);
const writePermission=requirePermission(s.permission);
router.use(auth);
router.get('/ordenes',readPermission,run((req)=>s.listOrders(req.context.empCod,req.query)));
router.get('/ordenes/:tempCod/:ordpnum',readPermission,run((req)=>s.getOrder(req.context.empCod,req.params.tempCod,req.params.ordpnum)));
router.get('/ordenes/:tempCod/:ordpnum/catalogo',readPermission,run((req)=>s.getOrderCatalog(req.context.empCod,req.params.tempCod,req.params.ordpnum,req.query.envase)));
router.get('/ordenes/:tempCod/:ordpnum/cajas',readPermission,run((req)=>s.getBoxes(req.context.empCod,req.params.tempCod,req.params.ordpnum,req.query)));
router.get('/ordenes/:tempCod/:ordpnum/resumen',readPermission,run((req)=>s.summary(req.context.empCod,req.params.tempCod,req.params.ordpnum)));
router.post('/ordenes/:tempCod/:ordpnum/cajas',writePermission,run((req)=>s.registerBox(req.context.empCod,req.context.login,req.params.tempCod,req.params.ordpnum,req.body)));
router.post('/ordenes/:tempCod/:ordpnum/generar-cajas',writePermission,run((req)=>s.generateBoxes(req.context.empCod,req.context.login,req.params.tempCod,req.params.ordpnum,req.body)));
router.post('/ordenes/:tempCod/:ordpnum/cerrar',writePermission,run((req)=>s.closeCapture(req.context.empCod,req.context.login,req.params.tempCod,req.params.ordpnum)));
router.get('/cajas/:tempCod/:caja',readPermission,run((req)=>s.getBox(req.context.empCod,req.params.tempCod,req.params.caja)));
router.get('/cajas/:tempCod/:caja/catalogo',readPermission,run((req)=>s.getBoxCatalog(req.context.empCod,req.params.tempCod,req.params.caja,req.query.envase)));
router.put('/cajas/:tempCod/:caja/reclasificar',writePermission,run((req)=>s.reclassifyBox(req.context.empCod,req.context.login,req.params.tempCod,req.params.caja,req.body)));
module.exports=router;
module.exports.readPermission=readPermission;
module.exports.writePermission=writePermission;
